service: informant-amp

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment: ${file(env.js):fetch}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectAcl
        - s3:ListBucket
      Resource: "arn:aws:s3:::${file(env.js):getBucketName}/*"

functions:
  updateReport:
    handler: handler.updateReport
    events:
      - http:
          path: updateReport
          method: post
  deleteReport:
    handler: handler.deleteReport
    events:
      - http:
          path: deleteReport
          method: post
  updateIndex:
    handler: handler.updateIndex
    events:
      - http:
          path: updateIndex
          method: post

resources:
  Resources:
    HtmlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(env.js):getBucketName}
        AccessControl: 'PublicRead'
        WebsiteConfiguration:
          IndexDocument: index.html

plugins:
  - serverless-offline