service: informant-amp

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment:
    BUCKET_NAME: ${self:custom.bucket}
    CMS_API_URL: ${self:custom.env.CMS_API_URL}
    PUBLIC_URL: ${self:custom.env.PUBLIC_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectAcl
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  updateReport:
    handler: handler.updateReport
    events:
      - http:
          path: updateReport
          method: post
  deleteReport:
    handler: handler.deleteReport
    events:
      - http:
          path: deleteReport
          method: post
  updateIndex:
    handler: handler.updateIndex
    events:
      - http:
          path: updateIndex
          method: post

resources:
  Resources:
    HtmlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: 'PublicRead'
        WebsiteConfiguration:
          IndexDocument: index.html

custom:
  env: ${file(env.js):fetch}
  bucket: informant-amp-web-${file(env.js):getStage}

plugins:
  - serverless-offline